server:
  # 端口
  port: 8081

# 配置 spring
spring:
  # s设置数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: demo
    password: 123456Ke
    hikari:
      # 连接池名
      pool-name: DataHikariCP
      # 最小空闲连接数
      minimum-idle: 5
      # 空闲连接存活最大时间，默认 600000（十分钟）
      idle-timeout: 180000
      # 最大连接数，默认 10
      maximum-pool-size: 10
      # 从连接池返回的连接的自动提交
      auto-commit: true
      # 连接最大存活时间，0表示永久存活，默认 1800000（三十分钟）
      max-lifetime: 1800000
      # 连接超时时间，默认 30000（三十秒）
      connection-timeout: 30000
      # 测试连接是否可用的查询语句
      connection-test-query: SELECT 1

# 配置 mybatis-plus
mybatis-plus:
  # 配置 Mapper 映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # 配置 MyBatis 数据返回类型别名（默认别名是类名）
  type-aliases-package: com.kekwy.oopt.server.pojo
  configuration:
    # 自动驼峰命名
    map-underscore-to-camel-case: false

# Mybatis SQL 打印（方法接口所在包，不是 Mapper.xml 所在包）
logging:
  level:
    com.kekwy.oopt.server: debug

jwt:
  # JWT 存储的请求头
  tokenHeader: Authorization
  # JWT 加解密使用的密钥
  secret: kekwy-secret
  # JWT 的超期限时间（60*60*24）
  expiration: 604800
  # JWT 负载中拿到开头
  tokenHead: Bearer

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.kekwy.oopt.server.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn